import { BadgeCheck, Mail, MapPin, Phone } from "lucide-react";
import data from "@/data/portfolio.json";
import { PageShell } from "@/components/page-shell";
import { SectionHeading } from "@/components/section-heading";
import { Card } from "@/components/ui/card";
import { CreativeMotion } from "@/components/creative-motion";
import { ToolkitSection } from "@/components/toolkit-section";
import ScrollFloat from "@/components/scroll-float";

export default function About() {
  return <PageShell><section className="px-5 pb-16 pt-28 md:px-8 md:pb-24 md:pt-36"><div className="mx-auto max-w-[1440px]"><div className="grid gap-10 md:grid-cols-[minmax(0,1fr)_420px] md:items-center"><div className="min-w-0"><p className="mono text-[10px] uppercase text-white/45">03 / About</p><ScrollFloat containerClassName="mt-6" textClassName="display text-4xl leading-[.95] sm:text-5xl md:text-7xl lg:text-8xl">Equal parts curiosity, clarity, and commercial intent.</ScrollFloat><div className="mt-10 grid gap-6 md:grid-cols-[minmax(0,1fr)_330px]"><p className="max-w-3xl text-base leading-8 text-white/65 sm:text-lg">Results-oriented marketing professional with six-plus years of hands-on experience building, executing, and refining campaigns across international markets. The work spans performance, content, brand, and the practical operations that make ideas deliver.</p><Card className="p-6"><p className="mono text-[10px] uppercase text-white/45">Contact</p><div className="mt-5 space-y-4 text-sm text-white/75"><a className="flex items-center gap-3 hover:text-white" href="mailto:1@leonpaulo.xyz"><Mail size={15}/>{data.profile.email}</a><p className="flex items-center gap-3"><Phone size={15}/>{data.profile.phone}</p><p className="flex items-center gap-3"><MapPin size={15}/>{data.profile.location}</p></div></Card></div></div><CreativeMotion className="about-motion"/></div></div></section><ToolkitSection/><section className="px-5 py-20 md:px-8 md:py-24"><div className="mx-auto max-w-[1440px]"><SectionHeading index="05" eyebrow="Education & trust" title="A grounded practice."/><div className="grid gap-3 md:grid-cols-2"><Card className="p-7"><p className="mono text-[10px] uppercase text-white/45">Education</p><ul className="mt-7 space-y-5 text-white/75"><li><b className="text-white">Digital Marketing</b><br/>IMS Proschool · 2021</li><li><b className="text-white">B.Com with Computer Applications</b><br/>CMS College of Science & Commerce / Bharathiar University · 2017-2021</li></ul></Card><Card className="p-7"><p className="mono text-[10px] uppercase text-white/45">Certifications</p><ul className="mt-7 space-y-4 text-white/75">{["Fundamentals of Digital Marketing - Google Digital Garage", "Public Relations - Unschool", "Content Writing & Marketing - Unschool", "Business Studies - CMS College of Science & Commerce"].map(c=><li className="flex gap-3" key={c}><BadgeCheck size={17} className="shrink-0 text-white/50"/>{c}</li>)}</ul></Card></div></div></section></PageShell>;
}
