import { BadgeCheck, Mail, MapPin, Phone, Sparkles } from "lucide-react";
import data from "@/data/portfolio.json";
import { PageShell } from "@/components/page-shell";
import { SectionHeading } from "@/components/section-heading";
import { Card } from "@/components/ui/card";
import { LanyardCard } from "@/components/lanyard-card";

const strengths = ["SEO & SEM", "Meta & Google Ads", "Content strategy", "Brand management", "Social media", "Market research", "Team management", "Creative direction"];

export default function About() { return <PageShell><section className="px-5 pb-16 pt-28 md:px-8 md:pb-24 md:pt-36"><div className="mx-auto max-w-[1440px]"><div className="grid gap-10 md:grid-cols-[minmax(0,1fr)_350px] md:items-start"><div className="min-w-0"><p className="mono text-[10px] uppercase text-white/45">03 / About</p><h1 className="display mt-6 max-w-5xl text-4xl leading-[.95] sm:text-5xl md:text-7xl lg:text-8xl">Equal parts <em>curiosity,</em> clarity, and commercial intent.</h1><div className="mt-10 grid gap-6 md:grid-cols-[minmax(0,1fr)_330px]"><p className="max-w-3xl text-base leading-8 text-white/65 sm:text-lg">Results-oriented marketing professional with six-plus years of hands-on experience building, executing, and refining campaigns across international markets. The work spans performance, content, brand, and the practical operations that make ideas deliver.</p><Card className="p-6"><p className="mono text-[10px] uppercase text-white/45">Contact</p><div className="mt-5 space-y-4 text-sm text-white/75"><a className="flex items-center gap-3 hover:text-white" href="mailto:1@leonpaulo.xyz"><Mail size={15}/>{data.profile.email}</a><p className="flex items-center gap-3"><Phone size={15}/>{data.profile.phone}</p><p className="flex items-center gap-3"><MapPin size={15}/>{data.profile.location}</p></div></Card></div></div><div className="hidden justify-self-end md:block"><LanyardCard/></div></div></div></section><section className="bg-[#121b21] px-5 py-20 md:px-8 md:py-24"></section></PageShell>; }
