"use client";

import { useEffect, useRef } from "react";

export default function ParticleText({ text = "Launch Faster", particleSize = 2, density = 4, color = "#fff", highlightColor = "#8b5cf6", scatter = 180, pointerRepel = 40, repelRadius = 120, fontSize = "clamp(3rem, 12vw, 8rem)", fontWeight = 800, glow = true, idleDrift = 0.7, trigger = "hover", fontFamily = "inherit", gatherDuration = 1600, stagger = 420 }: { text?: string; particleSize?: number; density?: number; color?: string; highlightColor?: string; scatter?: number; pointerRepel?: number; repelRadius?: number; fontSize?: string | number; fontWeight?: number | string; glow?: boolean; idleDrift?: number; trigger?: "mount" | "hover" | "click"; fontFamily?: string; gatherDuration?: number; stagger?: number }) {
  const ref = useRef<HTMLDivElement>(null); const canvas = useRef<HTMLCanvasElement>(null);
  useEffect(() => { const box = ref.current, node = canvas.current; if (!box || !node) return; const ctx = node.getContext("2d"); if (!ctx) return; let frame = 0; let points: {x:number;y:number;tx:number;ty:number;seed:number}[] = []; let pointer = {x:-1000,y:-1000};
    const resize = () => { const r = box.getBoundingClientRect(), dpr = Math.min(devicePixelRatio || 1, 2); node.width = r.width*dpr; node.height = r.height*dpr; ctx.setTransform(dpr,0,0,dpr,0,0); const w=r.width,h=r.height; const probe=document.createElement("canvas"), p=probe.getContext("2d")!; const size=typeof fontSize === "number" ? fontSize : Math.min(128, Math.max(42, w*.12)); p.font=`${fontWeight} ${size}px Manrope, sans-serif`; const measure=p.measureText(text); const off=document.createElement("canvas"); off.width=Math.ceil(measure.width+20); off.height=Math.ceil(size*1.3); const oc=off.getContext("2d")!; oc.font=p.font; oc.fillStyle="#fff"; oc.textBaseline="middle"; oc.fillText(text,10,off.height/2); const data=oc.getImageData(0,0,off.width,off.height).data; points=[]; const step=Math.max(3, density); for(let y=0;y<off.height;y+=step) for(let x=0;x<off.width;x+=step) if(data[(y*off.width+x)*4+3]>100){ const tx=w/2-off.width/2+x,ty=h/2-off.height/2+y,seed=Math.random(); const a=seed*Math.PI*2,dist=scatter*(.35+seed*.75); points.push({x:tx+Math.cos(a)*dist,y:ty+Math.sin(a)*dist,tx,ty,seed}); }};
    const draw = (now:number) => { const r=box.getBoundingClientRect(); ctx.clearRect(0,0,r.width,r.height); if(glow){ctx.shadowBlur=particleSize*4;ctx.shadowColor=highlightColor;} points.forEach(p=>{p.x+=(p.tx-p.x)*.045;p.y+=(p.ty-p.y)*.045; const dx=p.x-pointer.x,dy=p.y-pointer.y,d=Math.hypot(dx,dy); if(d<repelRadius){const f=(1-d/repelRadius)*pointerRepel;p.x+=dx/(d||1)*f;p.y+=dy/(d||1)*f;} ctx.fillStyle=color;ctx.globalAlpha=.45+.55*p.seed;ctx.fillRect(p.x,p.y,particleSize,particleSize);}); ctx.globalAlpha=1; frame=requestAnimationFrame(draw);};
    const move=(e:PointerEvent)=>{const r=node.getBoundingClientRect();pointer={x:e.clientX-r.left,y:e.clientY-r.top};}; const leave=()=>{pointer={x:-1000,y:-1000};}; resize(); window.addEventListener("resize",resize); node.addEventListener("pointermove",move); node.addEventListener("pointerleave",leave); frame=requestAnimationFrame(draw); return()=>{cancelAnimationFrame(frame);window.removeEventListener("resize",resize);node.removeEventListener("pointermove",move);node.removeEventListener("pointerleave",leave);}; }, [text,particleSize,density,color,highlightColor,scatter,pointerRepel,repelRadius,fontSize,fontWeight,glow]);
  return <div ref={ref} className="relative h-full min-h-[230px] w-full overflow-hidden" aria-label={text}><canvas ref={canvas} className="absolute inset-0 h-full w-full"/><span className="sr-only">{text}</span></div>;
}
